#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

(cd mcInletRandomTest; cleanApplication)

rm -f histogram.dat histograms.pdf generator.pyc log.mcInletRandomTest
