#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

compileApplication mcInletRandomTest

runApplication ./mcInletRandomTest/Make/$WM_OPTIONS/mcInletRandomTest
runApplication ./makePlots
