#!/bin/sh

# run from script directory
cd ${0%/*}

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

(cd ../tools/Rtime; cleanApplication)

for c in flow scalarsInit scalars
do
   cd $c
   cleanCase
   foamClearPolyMesh
   rm -rf 0 plots sets
   cd ..
done
