#!/bin/sh
#------------------------------------------------------------------------------
#                pdfFoam: General Purpose PDF Solution Algorithm
#                   for Reactive Flow Simulations in OpenFOAM
#
# Copyright (C) 2012 Michael Wild, Heng Xiao, Patrick Jenny,
#                    Institute of Fluid Dynamics, ETH Zurich
#------------------------------------------------------------------------------
# License
#    This file is part of pdfFoam.
#
#    pdfFoam is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) version 3 of the same License.
#
#    pdfFoam is distributed in the hope that it will be useful, but WITHOUT
#    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#    for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with pdfFoam.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#    RunFunctions
#
# Description
#    Common functions used by the Allrun tutorial scripts.
#
#------------------------------------------------------------------------------
# runParallel in 1.7.x does not handle additional arguments, this is from 2.1.x

runParallelFIX()
{
   APP_RUN=$1
   APP_NAME=${1##*/}
   shift

   if [ -f log.$APP_NAME ]
   then
      echo "$APP_NAME already run on $PWD: remove log file to re-run"
   else
      nProcs=$1
      shift
      echo "Running $APP_RUN in parallel on $PWD using $nProcs processes"

      ( mpirun -np $nProcs $APP_RUN -parallel "$@" < /dev/null > log.$APP_NAME 2>&1 )
   fi
}

