#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

(cd initPositionCorrectionTest; cleanApplication)

(
   cd simple
   cleanCase
   rm -rf 0
   cp -r 0.org 0
)

for c in limitedSimple Muradoglu ellipticRelaxation integrated
do
   removeCase $c
done
